typography_spectrum: 0.9086411679163575
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7790207131765783
  lightness: 0.7454288834705949
  saturation: 0.17952920170500875
  rhythmicContrast: 0.9444285759236664
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6303959689103067
analytics:
  google: null
  facebook: null
  twitter: null
name: G7 Power
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: G7 Power
description: Online Marketplace Supplier
purpose: []
