typography_spectrum: 0.18758545396849513
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.01598003669641912
  lightness: 0.09802830591797829
  saturation: 0.3493709098547697
  rhythmicContrast: 0.08214982063509524
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.05597897642292082
analytics:
  google: null
  facebook: null
  twitter: null
name: G7 Power
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: G7 Power
description: Online Marketplace Supplier
purpose: []
